### ISSUE TITLE
Take a look at all the possible loss of data warnings

### ISSUE THREAD

**Issue by pierce-smith1** [pierce-smith1/yok.scr#10]
All the C4244 and C4267s are making compilation very noisy. I have no idea if any of them speak to an actual issue - they probably don't, since everything has been going smoothly as far as I can tell - but we should do our due diligence, and get rid of all of them while we're at it.

**Comment by McAwesome123** [comment]
Can't say much about how good of a solution it is, but using explicit casts seems to get rid of the warning (#23)

**Comment by pierce-smith1** [comment]
That's far from solving all of them though.

**Comment by McAwesome123** [comment]
This feels more like "muting" them than solving them, just without _literally_ muting them
