### ISSUE TITLE
Have a check for if a palette in the index actually exists

### ISSUE THREAD

**Issue by McAwesome123** [pierce-smith1/yok.scr#68]
There should probably be a check for this so that when the index contains a palette that doesn't actually exist, the screensaver handles it properly instead of doing Weird Shit™.

Things I've seen happen so far as a result of this range from crashes on debug to Windows Defender popups(!) on release.

**Comment by pierce-smith1** [comment]
Is there is a reasonable way someone could do this to themselves? How did you run into this?

**Comment by McAwesome123** [comment]
It can happen if you somehow get a duplicate palette reference (and delete one of them) or if you're messing with the registry.
While we can't control the latter, the former is certainly possible in the current state of the screensaver.
But we are fixing those, so this might not really be necessary...?

**Comment by pierce-smith1** [comment]
Let's focus on fixing the cause and not the symptom.

**Comment by McAwesome123** [comment]
Of course. But if this ends up being something quick, I might still add it.
